# Generated by Django 6.0.2 on 2026-02-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='price',
            field=models.PositiveBigIntegerField(),
        ),
    ]
