# Generated by Django 6.0.2 on 2026-02-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_actor_director_movie_cast_movie_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_upcoming',
            field=models.BooleanField(default=False),
        ),
    ]
